ARDUINO_DIR=/usr/share/arduino
BOARD_TAG=uno
MCU=atmega328p
F_CPU=16000000L
ARDUINO_PORT=/dev/ttyACM0
AVRDUDE_ARD_PROGRAMMER=arduino
AVRDUDE_ARD_BAUDRATE=115200
ARDUINO_LIBS=ByteOrder Buffer ByteBuffer ArrayByteBuffer
VARIANT=standard

include /usr/share/arduino/Arduino.mk
